
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Jose M Yanez  ## put your name
title: 'Computer Science Student'  ## your title
location: El Paso, Texas


## Social Profiles
#facebook: http://www.facebook.com  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/jose-yanez-968244109/  ## your linkedin account url
github: https://github.com/jmyanez



# Update all the sections by editing the files inside _includes folder.
